### ISSUE TITLE
Adding a license?

### ISSUE THREAD

**Issue by hr-oss** [DPS2004/ld45#1]
Howdy!

Love this game. I know it’s an older repo, but I was curious if you’d like to add a license to it, so people don’t have to worry about getting sued if people use it?😆

Here’s a tutorial on how to add one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you !

**Comment by DPS2004** [comment]
Added, thanks for beinging it up!
That being said, I don't really suggest basing any projects on this, given how messy the code is. It was my first real game in PICO-8, and doesn't follow a lot of what could be considered best practices for the engine.
